# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy
    - go mod download
    - go generate ./...

builds:
  - id: linux
    main: ./cmd
    binary: azrb
    goos:
      - linux
    goarch:
      - amd64
  - id: windows
    main: ./cmd
    binary: azrb
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: darwin
    main: ./cmd
    binary: azrb
    goos:
      - darwin
    goarch:
      - amd64

archives:
  - id: default
    builds:
      - linux
      - darwin
      - windows
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: "false"
  footer: |

    ---
    
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
