name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Download Dependencies
        run: go mod tidy

      - name: Verify Dependencies
        run: go mod verify

      - name: Build
        run: go build -v .

      - name: Run Tests
        run: go test -v ./...
